import {Task} from './Task.js';


export let tasks = [
    new Task("ベビーカー","wandelwagen"),
    new Task("ブランケット","wollen dekentje"),
    new Task("ベビー用敷きパッド","babybed pad"),
    new Task("ベビー用シーツ、カバー","babybedje lakens en hoezen"),
    new Task("ベビー布団","dekbed voor baby"),
    new Task("キルトパッド","dekbedovertrek"),
    new Task("防水シーツ","waterdichte lakens"),
    new Task("スウィングベッド","schommel bed"),
    new Task("スリーパー","pyjama"),
    new Task("ケープ","baby capes"),
    new Task("ベビー肌着","baby ondergoed"),
    new Task("ロンパース","rompertjes"),
    new Task("ボディスーツ","bodysuit"),
    new Task("フットマフ","voetenzak"),
    new Task("よだれかけ","slabbetje"),
    new Task("布おむつ","cloth diapers"),
    new Task("おむつカバー","luier dekking"),
    new Task("おむつ替えシート","luier verschoningslaken"),
    new Task("おむつ用ゴミ箱","luier prullenbak"),
    new Task("おしりふき","babydoekjes"),
    new Task("ベビーバス","baby bad"),
    new Task("バスチェア","bad stoel"),
    new Task("湯温計","warmwaterthermometer"),
    new Task("ベビー爪切り","baby nagelknipper"),
    new Task("沐浴布","bad katoenen gaas"),
    new Task("ガーゼハンカチ","gaas zakdoek"),
    new Task("授乳クッション","borstvoedingskussen"),
    new Task("哺乳瓶ブラシ","borstels voor zuigflessen"),
    new Task("哺乳瓶用洗剤、哺乳瓶消毒グッズ","wasmiddelen/steriliseren voor zuigflessen"),
    new Task("哺乳瓶用乳首","producten voor het steriliseren van zuigflessen"),
    new Task("哺乳瓶用乳首","zuigflessen"),
    new Task("体温計","thermometer"),
    new Task("マザーズバッグ","moeders tas"),
    new Task("ベビーハンガー","baby hanger"),
    new Task("鼻吸い器","neusaspirator"),
    new Task("抱っこひも","babydraagzak"),
    new Task("おくるみ","swadle"),
    new Task("長肌着","lange onderbroek(wool?)"),
  ];
